<?xml version="1.0"?>
<package format="3">
  <name>tracer2_description</name>
  <version>1.0.0</version>
  <description>URDF meshes and description for the Agilex Tracer 2 mobile base.</description>
  <maintainer email="TODO@email.com">TODO</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
